
class EmailNotMatch(Exception): ...


class InvalidCountryFormat(Exception): ...


class InvalidPhoneFormat(Exception): ...


class InvalidPinFormat(Exception): ...

class UserAlreadyRegistered(Exception): ...


class InvalidCredentials (Exception):...

class UserNotFound (Exception):...