
class EmailNotMatch(Exception): ...


class InvalidCountryFormat(Exception): ...


class InvalidPhoneFormat(Exception): ...


class InvalidPinFormat(Exception): ...

class UserAlreadyRegistered(Exception): ...


class InvalidCredentials (Exception):...

class UserNotFound (Exception):...

class InvalidCredentialsToken (Exception):...

class  TokenExpired(Exception):...

class InvalidToken(Exception):...

class CurrentlyUsedPassword(Exception):...
class UserUpdateFailed(Exception):...
